name: spellcheck
on:
  pull_request:
  workflow_dispatch:
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@0.23.0
        with:
          config_path: .github/spellcheck/config.yml
          task_name: Markdown